name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update the apt repos
      run: sudo apt-get update -y
    - name: install dependencies
      run: sudo apt-get install libtool libboost-all-dev -y
    - name: autoconfig
      run:  ./autogen.sh
    - name: configure (without wallet)
      run: ./configure --disable-wallet
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
