name: Build and upload to an artifact for x64 Windows

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Update the apt repo
        run: |
          sudo add-apt-repository ppa:bitcoin/bitcoin
          sudo apt-get update -y
      - name: Install dependencies
        run: sudo apt-get install libtool libboost-all-dev build-essential autotools-dev automake pkg-config bsdmainutils curl git nsis g++-mingw-w64-x86-64 qtdeclarative5-dev qtbase5-dev qttools5-dev qtdeclarative5-dev qt5-default libzmq3-dev libminiupnpc-dev software-properties-common libssl-dev libevent-dev libdb4.8-dev libdb4.8++-dev -y
      - name: Depends make
        run: |
          #laittaa automaattisen tilan k채ytt채m채채n posixia
          sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-gcc x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-win32 60
          sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-gcc x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix 90
          sudo update-alternatives --config x86_64-w64-mingw32-gcc 
          sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-g++ x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-win32 60
          sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-g++ x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix 90
          sudo update-alternatives --config x86_64-w64-mingw32-g++
          
          cd depends
          sudo make HOST=x86_64-w64-mingw32
          cd ..
      - name: Autoconfig
        run:  sudo ./autogen.sh
      - name: Configure 
        run: sudo CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
      - name: Make
        run: sudo make
      - name: Make installer
        run: | 
          sudo make deploy
          ls -R
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: "*.exe"
          if-no-files-found: error
          retention-days: 90
